name: CD
on:
  push:
    branches: [main]
jobs:
  cd:
    uses: ../finance-infra/.github/workflows/reusable-cd.yaml@main
    with:
      java-version: "21"
      service-name: finance-gateway
    secrets:
      ZEABUR_API_TOKEN: ${{ secrets.ZEABUR_API_TOKEN }}
      ZEABUR_SERVICE_ID: ${{ secrets.ZEABUR_SERVICE_ID }}
      ZEABUR_PROJECT_ID: ${{ secrets.ZEABUR_PROJECT_ID }}
